# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

<% case node['redmine']['database']['type'] -%>
<% when "mysql", "mysql2" -%>
production:
  adapter: <%= node['redmine']['database']['type'] %>
  database: <%= node['redmine']['database']['name'] %>
  host: <%= node['redmine']['database']['hostname'] %>
  socket: <%= node['redmine']['database']['socket'] %>
  username: <%= node['redmine']['database']['username'] %>
  password: <%= node['redmine']['database']['password'] %>
  encoding: utf8

development:
  adapter: <%= node['redmine']['database']['type'] %>
  database: <%= node['redmine']['database']['name'] %>
  host: <%= node['redmine']['database']['hostname'] %>
  username: <%= node['redmine']['database']['username'] %>
  password: <%= node['redmine']['database']['password'] %>
  encoding: utf8

<% when "sqlite" -%>
production:
  adapter: sqlite3
  dbfile: db/production.db
<% end -%>
